### ISSUE TITLE
Save button does not work on Safari (macOS)

### ISSUE THREAD

**Issue by KizzyCode** [LostRuins/lite.koboldai.net#21]
The save button does nothing on Safari (macOS). To be more precise: If clicked, it generates a blob-resource, which can be inspected/opened via the developer console, but it does not trigger a download nor is there any visible change in the UI.

I'm not a web-frontend-dev, so If you need some more information or want me to do some additional tests, I'm happy to help 😊

**Comment by LostRuins** [comment]
Seems like Apple browsers are implementation file download restrictions. Can anyone else confirm that the save link is broken on Safari (desktop)? If so I will switch it to the fallback downloader which presents the user with a link to save as instead.

**Comment by LostRuins** [comment]
safari save button should be working now, it was fixed some time back. but firefox on mac still has some issues.
