### ISSUE TITLE
question/suggestion

### ISSUE THREAD

**Issue by scavru** [LostRuins/lite.koboldai.net#24]
you're not considering a connection to oobabooga web ui API?

**Comment by LostRuins** [comment]
Oobabooga does have an extension that provides a Kobold compatible API, so if you use that then it will work with Lite.

**Comment by scavru** [comment]
Can you give me a link? I went all over google, found https://github.com/Maykeye/hoperator, but Kobold can see it, but it's not working properly and LITE doesn't even see it.

**Comment by henk717** [comment]
This should be --api if that no longer works ooba would have to fix it.

Alternatively give KoboldAI itself a try, Koboldcpp has lite included and runs GGML models fast and easy. KoboldAI United also includes Lite and runs the latest huggingface models including 4-bit support. And if you specifically want to use GPTQ/Exllama this can be done with the 4bit-plugin branch from 0cc4m.
