### ISSUE TITLE
Cannot use angle brackets in Instruct Mode sequences?

### ISSUE THREAD

**Issue by aleksusklim** [LostRuins/lite.koboldai.net#27]
For example, I want my Start Seq. to be `\n> ` and my End Seq. to be `\n< `, but this messes up the textarea badly, creating infinite `<span class="txtchunk"<span class="color_gray">></span><span class="txtchunk"<span class="color_gray">></span><span class="txtchunk"<span class="color_gray">></span>` after each mouse click!

Actually, I'm trying to use this made-up game template:
```
You are the roleplay storyteller. I will tell you my actions after ">", and you will reply with the detailed description of outcomes after "<". First, give me the setting!

< You are a noble knight. The king have sent you to kill the dragon. Now you are in the forest.
> I look around.
< As you look around, 
```

In works in Story Mode, and kinda-works in Chat Mode (I had to replace `>` and `<` with `>:` and `<:`).
Is there a bug with HTML-escaping somewhere?

**Comment by LostRuins** [comment]
Should be fixed - I used a very hacky method but i think it should work.

**Comment by aleksusklim** [comment]
Thank you! It works in **koboldcpp-1.41**.

By the way, do you know why sometimes I get line-feeds after model output, even if I set `Trim Whitespace`?
For example, even though my conversation looks fine in `Instruct Mode`, when I enable `Allow Editing`, it shows occasional newlines in history:

```
> AAA
< BBB
> CCC
< DDD

> EEE
< FFF

> DDD
< GGG
```

**Comment by aleksusklim** [comment]
@LostRuins, follow-up for my previous question above:

Am I right that in Instruct Mode I can leave input field blank and click Submit – for the system to NOT generate new pair of instruct-response, but merely to "continue" current line, from whatever state it is currently?

That, for example, I can edit model's output to `Sure thing! To` – and force it to continue it's faked answer.

If so, then I have an issue here: **sometimes, such empty submit puts a newline \n at the end of the history.**

So the model sees linefeed and most likely generates new instruct tag, forcing the generation to stop. No continues, just switching turns.
This newline is invisible in the interface (even with editable checkbox set). It cannot be deleted. It is always present after when it appeared in current line.

But! Sometimes, it is not there. And in this case, empty submit continues just fine. Perfectly.
But sometimes it does not if this newline sticks, I don't understand how to reliably trigger it.

If you want, I can test that further, and open an issue titled "conversation history puts an invisible line break at the end sometimes".
Or maybe you know what could be wrong here, right away?

**Comment by LostRuins** [comment]
@aleksusklim yes that is correct - what you can try is to enable "Trim Whitespace" which will get rid of trailing newlines in the UI. If you toggle edit mode, the newline should also be stripped when the text is merged.

**Comment by aleksusklim** [comment]
My `Trim Whitespace` is enabled (and always was), that's the point!

Is is not working for me? Anyway, there is NO newlines visible in edit mode. But present during generation.

**Comment by LostRuins** [comment]
Trim whitespace should be fixed and working better now (on web lite), please try again.

**Comment by aleksusklim** [comment]
> Trim whitespace should be fixed and working better now (on web lite), please try again.

No, I can confirm that it didn't help. I downloaded 8b02c6231894843252ee4d6912cb59052e0b405e and pointed it to 1.44.2 instance.
Instruct mode, `mythalion-13b.Q5_K_M.gguf`, with `Trim Whitespace` enabled but `Trim Sentences` disabled.
`Allow Editing` with `Raw Instruct Tags`
Extra Stopping Sequence was `<||$|||`, so it would stop early on switching actors).

Initially I set my `Start Seq.` to `\n<|user|>` and `End Seq.` to `\n<|model|>`. I had a history like this after first turn:

```
<|system|>AAA
<|user|>BBB
<|model|> CCC
```

Then I submit `DDD` and  `FFF` to get:
(I masked actual texts, but here I preserved spaces before model responses, looks like they are from the model itself)

```
<|system|>AAA
<|user|>BBB
<|model|> CCC

<|user|>DDD
<|model|> EEE

<|user|>FFF
<|model|> GGG
```

So, newlines appear (they are present in console dump too). Okay, I just changed `Start Seq.` to `<|user|>` without newlines. This gives smooth

```
<|user|>HHH
<|model|> III
<|user|>JJJ
<|model|> KKK
<|user|>LLL
<|model|> MMM
```

up the the point where suddenly there was no newline between:

```
<|model|> NNN
<|user|>OOO
<|model|> PPP<|user|>QQQ
<|model|> RRR
```

When this happened, console showed `(EOS token triggered!)` in previous generation instead of `(Stop sequence triggered: <<>)`

Each time generation completes by stop sequence instead of EOS token – I cannot make it continue the last reply, because the invisible line-feed always appears at the end of the history, even if I'll cut the last line in the middle.

For me, it is like the model replies with `…TEXT\n<|user|>` and that gets trimmed to `TEXT\n` by stop-sequence resolver; then gets rendered as `…TEXT` because of newline trimming, but for some reason gets submitted with a newline again. This newline at the end is also appears in JSON with saved history (when is was not stopped by EOS in the last try).
Do you have any function where you add newlines back to the end?

Still, I can create an issue titled "Stopping by Stop Sequence sometimes creates a permanent line-feed at the end of the history, while stopping by EOS tokes does not" and prepare an exact reproductible history at zero temp, since now I'm pretty much confident in it.

**Comment by LostRuins** [comment]
Thanks for the detailed explanation, I see how it's happening now. Yes, trim whitespace is indeed applied *before* the final stop sequence handler. Also in CHAT mode, a newline is automatically inserted whenever a turn message is submitted.

I have changed the whitespace trimmer to trigger after the stop sequence handler. Can you help check if that solves your issue?

**Comment by aleksusklim** [comment]
Yes! Actually, now the gameplay is smooth, with `\n<|user|>` working as expected, allowing for continuation of any phrase, and never putting a newline before the submitted input.

Thank you!!

**Comment by aleksusklim** [comment]
Um-m, @LostRuins, is the newline bug stroke back?

I am playing in v1.55.1, Instruct mode, with `\n<|user|>` and `\n<|model|>`, and `Trim Whitespace` enabled.

When the model ends its turn with a line-feed and starts to write `<|user|>`, the generation stops and that newline disappears. But!

If I'll send the next input right away – the mysterious newline will be inserted directly before my line.
(When this happens, you can abort and press "Back" twice to return to the same buggy position)

Instead, if I'll click to the history textbox, change something there and click back to the input field – the bug disappears, and the next generation would be normal.

As before, when the model ends the line by EOS token – this line-feed is not appearing too.

**Comment by LostRuins** [comment]
Are you sure it's a mysterious newline, and not just a browser formatting artifact? To confirm it's a newline, enter edit mode and see what the actual context is - or check in the terminal, do you see an extra `\n` added?

If not, it could be just the way text is rendered after the instruct avatar.

**Comment by aleksusklim** [comment]
Yes, I confirmed it in the console.
It shows `.\n\n<|user|>`, the newline gets inserted before my text.

Meanwhile, if I'll put `\n` as a stop sequence (which was empty before, relying on automatic tracking of my `\n<|user|>`) – then the generation stops right at the newline fine; even if it would be `\n<|user|>`… Wait a second.

Console also shows `, "stop_sequence": " ["<|user|>", "<|model>", "\n<|user|>"],`
– Are auto stops are detected badly? You're losing newline there!

It thinks the default stop sequence is `<|user|>` while my start sequence is `\n<|user|>`!

**Comment by LostRuins** [comment]
No, that is intended behavior. The auto stop sequences submitted when extracted from chat and instruct tags do not have any whitespace.

https://github.com/LostRuins/lite.koboldai.net/blob/main/index.html#L8835

That's because some models are terrible at following the prompt formatting exactly, so if you need a perfect match they can sometimes fail to trigger.

**Comment by aleksusklim** [comment]
Why "Trim whitespace" did not remove the line feed, then?

**Comment by LostRuins** [comment]
Is it possible it's due to the order of operations of the trimming? Right now they are carried out in this sequence:
- Trim stop sequences
- Trim whitespace
- Trim mode specific tags (instruct tags, adventure tags, chat names)

Refer to 
https://github.com/LostRuins/lite.koboldai.net/blob/main/index.html#L9595

It might be helpful to breakpoint the `handle_incoming_text()` function and step through each line, to see whether it's behaving correctly.

**Comment by aleksusklim** [comment]
I traced it!

```js
// assume gentext is TEXT\n<|user|>
gentxt = trim_extra_stop_seqs(gentxt,true); // "TEXT\n<|user|>"
…
gentxt = trim_extra_stop_seqs(gentxt,false); // "TEXT\n<|user|>"
…
if (localsettings.trimwhitespace) {
  gentxt = gentxt.replace(/[\t\r\n ]+$/, ''); // "TEXT\n<|user|>"
}
…
if (localsettings.opmode == 4)
{
  let st = get_instruct_starttag(true); // "<|user|>"
  let et = get_instruct_endtag(true); // "<|model|>"
  let found = gentxt.indexOf(st); // 5
  let splitresponse = [];
  if (found != -1)
  {
    splitresponse = gentxt.split(st); // ["TEXT\n",""]
    gentxt = splitresponse[0]; // "TEXT\n"
  }
  …
}

let gentxtspeak = gentxt; // "TEXT\n"
```

Looks like special tags trimming is done after whitespace trimming, which did nothing useful when a tag was still present.

Do you think `localsettings.trimwhitespace` branch should be moved to the end of the function? Instruction handling in `localsettings.opmode==4` will get rid of anything after a found tag, so extra spaces there won't hurt.

Though I cannot tell that for sure for `opmode==2` and `opmode==3` branches, there you have more special handlings of spaces and newlines (so it would need either strict proof or dedicated testing to be sure that moving whitespace trimming won't break anything subtly).

On the other hand, you can just copy trimwhitespace branch to the end of the function also, so it would be called twice.
Even safer is putting its copy just at the end of opmode==4 branch, so that it affects only Instruct mode, without ever touching anything else.

P.S.
You don't have to use .split when you already done .indexOf since you can just `gentxt=gentxt.substring(0,found);` with its value; otherwise just always do `gentxt=gentxt.split(st)[0]` without thinking about whether it founds something or not!

**Comment by LostRuins** [comment]
Yeah, fair enough. I will run the whitespace trimmer twice, once before the tag trimmer and once after. Hopefully this will catch and solve edge cases like yours. Do you forsee any issues with that?

**Comment by aleksusklim** [comment]
> Do you forsee any issues with that?

Thanks, everything seems good.

Just a quick request (though I know it's a wrong place): in koboldcpp server GUI, when choosing a model file in Open dialogue window, even if I'll click CANCEL – it clears the textbox with older path!
Not canceling the "changing" of the file to load, but clearing it away, without any undo. Such inconvenient after choosing a correct .kcpp already: I found myself clicking the model button accidentally (or to just view the folder with my models quickly), canceling it and hitting Launch which pops up the same dialogue again, I cancel it (wishing to restart from pressing Load to choose the config again) but everything closes, ugh!..
I cannot just choose the correct model, since I may even not remember what it was as I started from loading an old config (and the visible portion of the path may not show the actual filename of the model in GUI)

**Comment by LostRuins** [comment]
Okay will try to fix that too

**Comment by aleksusklim** [comment]
Tried updated Lite, can't see the wrong newline appearing anymore under the same circumstances, thanks!
(Turns out for Metharme format an explicit `\n` in the stoplist works better, since the model sometimes misspells those sequences when hallucinating)

**Comment by aleksusklim** [comment]
Ugh, I tried mistral format as `\n[INST]` + `[/INST]\n` (I wanted the model to reply on a new line, rather than on current one), and it works only before edition: the turn itself produces `…history\n[INST]prompt[/INST]\n` but if I'll abort and edit to continue generation – it will become `…history\n[INST]prompt[/INST]` without a newline.

Hmm… I don't see any other way to fix this aside of "check if the stripped history ends with an exact ending sequence but stripped too, and if it is – delete and re-add the ending sequence" (maybe worth checking for starting sequence too because the user might want to change places)

Anyway, good models seem to learn quickly from existing history, and manual addition of a few proper line breaks will make the model to insert them on its own as the first token in each response.
