### ISSUE TITLE
Split "Trim Whitespace" into two options.

### ISSUE THREAD

**Issue by TaleirOfDeynai** [LostRuins/lite.koboldai.net#39]
The "Trim Whitespace" setting currently does two things to the context sent to the AI that really shouldn't be together:
1. It removes trailing newlines in the context sent to the AI.
2. It compresses multiple sequential newlines together into a single newline.

The first one is really kinda important to have enabled, because the use of the `contenteditable` attribute leads to an unwanted (and invisible) `<br />` element randomly being added to the end of the story textbox in the HTML which get turned into a `\n` character when converted into the AI's context (at least on Chromium-based browsers).  So, I typically want this to always be on to minimize the disruptive consequences this can have when trying to get an AI to do sentence continuation.

However, the second one can be bad to always have enabled, depending on your model.  Some models benefit from the formatting of double-newlines, since they are strong cues of major shifts in context. Like, if I'm writing in a markdown format, you would typically use a double newline before a new section header and many AI *really* want to use this pattern.

Also the memory and world-info are exempted from newline compaction and I will often use the AI to help me build these before pasting it in there.

When using Kobold Lite to write something where double-newline formatting is helpful, it is quite disruptive because:
- ...if I have "Trim Whitespace" enabled, the AI gets an input that might be sub-optimal, which can lead to:
  - ...it not outputting in the format I want requiring me to fix it myself.
  - ...it generating kinda bizarre or unexpected output because it's actually expecting more formatting than it is getting.
- ...if I have it disabled, a damn `<br />` often manifests at the end of the textbox that I need to use the dev-tools to delete before I can submit to the AI. For some reason, the old trick of hitting `enter + enter + left-arrow + delete + backspace` to get rid of it doesn't work anymore!

**So, this suggestion is to split "Trim Whitespace" into two options:**
- "Trim Trailing Whitespace" just trims the end of the story section to clean it up.
- "Compact Newlines" converts multiple sequential newlines into a single newline. This still only affects the story text; memory and world-info will preserve newlines as it does now.

It would be nice if the bug where the trailing `<br />` element is invisibly added and can't be removed were just fixed, but I know that isn't straight-forward because of the inconsistent implementations of `contenteditable` between browsers.  Splitting "Trim Whitespace" into two options is probably the easiest workaround.

**Comment by LostRuins** [comment]
Excellent suggestion. Added to lite, and will be available in the next koboldcpp release.
