### ISSUE TITLE
Aesthetic and Messenger UI don't support newlines in message

### ISSUE THREAD

**Issue by Auvski** [LostRuins/lite.koboldai.net#40]
When I set the UI style to "aesthetic" in both chat mode and instruct mode, I find that there doesn't seem to be a way to insert a newline in the user message text field. I have tried the following:

* Enter
* Ctrl+Enter
* Shift+Enter

both with, and without, the "Enter Sends" box checked. In all cases I either (a) send a message or (b) do nothing, instead of the desired result of inserting a newline.

This is not an issue in the "Classic" UI, which correctly interprets Shift+Enter as inserting a newline.

I have checked and my keyboard is definitely sending the correct keycodes of 13 (for Enter) and 10 (for Ctrl+Enter).

**Comment by LostRuins** [comment]
This is correct - the messenger interface currently does not support multiline input, as that would require making it resize correctly (it's on the backlog). For now you'd have to use the classic ui.
