### ISSUE TITLE
OpenRouter Throwing an error with Some models:

### ISSUE THREAD

**Issue by jeffkelly2020** [LostRuins/lite.koboldai.net#45]
Hello,
Over the past couple days, I've been seeing an error when using Lite with Certain models on OpenRouter. In particular, this is happening with alpindale/goliath-120b and xwin-lm-70b, maybe others I haven't found so far. When I try to generate text with either of these models, I see the following:
Error occurred during text generation: {"error":{"message":"{\n \"error\": {\n \"message\": \"Bad Arguments. ’logit_bias’ not yet supported.\"\n }\n}\n","code":400}}.
Both of these models worked fine as of several days ago, and most other models still seem to be working as of today. Not sure if something changed in Lite or on the OpenRouter side. Does anyone have any idea what's going on?

**Comment by LostRuins** [comment]
Hi, can you please try again and see if this is resolved? thanks.

**Comment by jeffkelly2020** [comment]
Hi,

Still not working, but now it’s a slightly different error. It seems to try for a few seconds longer, and then simply aborts:

Error while submitting prompt: AbortError: The operation was aborted.

**Comment by LostRuins** [comment]
Then I think it's an OpenRouter issue

**Comment by jeffkelly2020** [comment]
It seems to be working now for whatever reason.

Thanks for having a look!

**Comment by jeffkelly2020** [comment]
Actually, I believe now the change you made did resolve the issue. I’m still occasionally getting the generic “The operation was aborted” error, but I think that’s simply due to OpenRouter overload. I have not seen the “logit_bias’ not yet supported” error at all today.
