### ISSUE TITLE
Selecting a whole line and replacing it also replace the previous new line feed

### ISSUE THREAD

**Issue by jojorne** [LostRuins/lite.koboldai.net#50]
Let's say we have this:
```
text a

text b
```
If you select "text b", the entire line, and paste something, you'll get this result:
```
text a
new text
````
And by doing again, selecting "new text" and pasting something, you'll get this:
```
text asomething
```

**Comment by LostRuins** [comment]
Doesn't happen to me. what browser are you using?

**Comment by jojorne** [comment]
Okay... I tested on Edge and Chrome. It only happens on Firefox.

**Comment by jojorne** [comment]
I think that it's a bug with Firefox itself.

![image](https://github.com/LostRuins/lite.koboldai.net/assets/18329136/5eaf4e5f-f485-4590-9ffb-9ea81a9b1db0)
old text
![image](https://github.com/LostRuins/lite.koboldai.net/assets/18329136/21ae1e27-4ebe-41ad-b9ac-6adb1bc1d434)
new text

There was nothing in lite that changed the text before the merge_edit_field method, right?

**Comment by jojorne** [comment]
I think there is a bugzilla open with the suggestion to listen to "beforeinput".

**Comment by LostRuins** [comment]
Could you link the to the bugzilla issue?

**Comment by jojorne** [comment]
If you disable the `merge_edit_field()` event, it fix the behavior. The `white-space: pre-wrap;` prevents `<br>` from being inserted.
My conclusion is that `merge_edit_field()` modifies the content in a way that Firefox doesn't know how to handle.

**Comment by LostRuins** [comment]
If you disable "autosave" does it still happen?

**Comment by jojorne** [comment]
> If you disable "autosave" does it still happen?

Yes. It still happens.

**Comment by LostRuins** [comment]
Okay I took some time to look into this, and I don't think I am able to fix it. Even when I remove all my copy-paste handling and use the default one, it still happens in firefox. In fact, looking at other online examples this is happening too. For example:

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_global_contenteditable

The same effect occurs. I think its just a bug in firefox itself.

**Comment by jojorne** [comment]
I don't know javascript but...
```javascript
			document.querySelector('meta[name="viewport"]')
			.setAttribute("content","width=device-width, initial-scale=1, maximum-scale=1");
		}

		//fix for replacing text in firefox
		{
			document.getElementById("gametext").addEventListener("beforeinput", function(e) {
				if (e.inputType == "insertText") {
					e.preventDefault();
					let text = e.currentTarget.innerText;
					let selection = window.getSelection();
					let selectionStart = selection.anchorOffset;
					let selectionEnd = selectionStart + selection.rangeCount;
					e.currentTarget.innerText = `${text.slice(0, selectionStart)}${e.data}${text.slice(selectionEnd)}`
				}
			});
		}

		//fix for copy paste text in firefox, and also to prevent pasting rich text
		{
			document.getElementById("gametext").addEventListener("paste", function(e) {
				e.preventDefault();

```
Maybe this will help?

**Comment by LostRuins** [comment]
Unfortunately this won't work. Not only does it not correctly preserve edit history for redo/undo, it's also triggering on every singe key input and inserting characters at the wrong index. If you're trying to handle text pasting the event type should be `insertFromPaste` not `insertText` (but that does not cover all scenarios, because it's possible to replace a line of text by typing normally too)
