### ISSUE TITLE
Simple ready to go preset?

### ISSUE THREAD

**Issue by Seantourage** [LostRuins/lite.koboldai.net#51]
Is there anyways I can pre-configure koboldai with a supplied json or character card, endpoint and model settings so a user can instantly chat with the character I choose using my supplied endpoint?

I tried digging through the code, but it's a novel to figure out with my limited skills.

Thanks

**Comment by LostRuins** [comment]
Yes you can - you can export settings inside the json file which anyone who imports will get. If you're using koboldcpp, you can preconfigure a ready made save file using the `--preloadstory` option

**Comment by Seantourage** [comment]
Nice I'll take a look into that. Thanks!

**Comment by Seantourage** [comment]
Works great. Is there any way to get the unembedded koboldai.lite to auto connect to the endpoint and load the story?

I tried changing the following settings in the html file but it still wants me to pick an AI on first load.

saved_kai_addr: "http://localhost:5001",
prev_custom_endpoint_type: 1

Is there a way to have it autoconnect to the endpoint without a prompt even if

			let loadedsettingsjson = localStorage.getItem(STORAGE_PREFIX + "settings");
			let loadedstorycompressed = old loadlocalStorage.getItem(STORAGE_PREFIX + "story");

are both empty on first load?

Thanks a ton!

**Comment by LostRuins** [comment]
For that you can simply use URL params. Here's an example that tries to connect to a host on 192.168.1.50 at port 5005:

`https://lite.koboldai.net/?local=1&port=5005&host=192.168.1.50`

This will work when running on any domain, not just the official one. You can simply override any of the URL params and it will load accordingly.

**Comment by LostRuins** [comment]
FYI, You can also launch Lite already filtered to a specific set of scenarios. For example:

https://lite.koboldai.net/?scenario=niko

likewise, you can utilize a character card scenario downloaded from chub, for example:

https://lite.koboldai.net/?chub=shaolan98/lara-lightland

Many setups can be arranged solely via the URL parameters.

**Comment by Seantourage** [comment]
Great info!
