### ISSUE TITLE
XTTS options not saved

### ISSUE THREAD

**Issue by Seantourage** [LostRuins/lite.koboldai.net#55]
When re-opening the advanced settings menu after setting a XTTS API and voice the TTS setting shows Microsoft Luna.

Additionally when reloading the page, the XTTS options are not saved in local browser storage kaihordewebui_settings requiring it to be re-configured again.

It would also be nice if along with the default settings (below) you could also specify a speaker/voice and have xtts auto connect:

Current:
Line 3347:  var xtts_base_url = " http://127.0.0.1:8020";
Line 3398:  speech_synth: 100, //0 is disabled, 100 is xtts

Add:
default_voice = "female";  (or female.wav, staying consistent with the dropdown voice dialog)

If my skills were better I'd submit code, but thought I'd offer as much info as i could with the bug report/feature request.

Also does the current implementation utilize streaming similar to SillyTavern? I'm assuming not, but just wanted to check.

Thanks again. As I get more familiar maybe I can submit code one of these days.

**Comment by LostRuins** [comment]
No streaming is currently used. As of now, custom XTTS endpoint settings are not saved to settings and are lost on restart.

**Comment by LostRuins** [comment]
Fixed, please try.

**Comment by Seantourage** [comment]
Still having issues, but I think it's due to the number of TTS voices my OS has installed.

I've patched up the code but am having one issue that I can't figure out. Any chance you can reach out via discord for a quick moment so i can post the changes?

Username is seantourage on discord

**Comment by LostRuins** [comment]
Sure, sent you a friend request.
