### ISSUE TITLE
Trying to use Together AI Instead of OpenAI.

### ISSUE THREAD

**Issue by jeffkelly2020** [LostRuins/lite.koboldai.net#60]
Hello,
Together AI is supposedly compatible with OpenAI's API, see here:
https://docs.together.ai/docs/openai-api-compatibility
However, when I try to use it in Lite, it doesn't work. I select Open AI as the custom endpoint, specify https://api.together.xyz/v1 as the API Url, and enter my Together AI key. If I then press fetch list, the list never updates, still reflecting the OpenAI models.
Am I missing something, or is this just not going to work for some reason?
Thanks,

**Comment by LostRuins** [comment]
Fixed. Their format is actually incorrect, but I added a workaround to make it work.

**Comment by jeffkelly2020** [comment]
Awesome. Thanks!
