### ISSUE TITLE
Include input prompt contents and streaming text into saved JSON (and the model name too!)

### ISSUE THREAD

**Issue by aleksusklim** [LostRuins/lite.koboldai.net#63]
When a long-lasting generation is in progress, I expect the yellow text to appear for quite some time. Thank you for fixing its disappearing in case of broken connection, now I can be sure that I won't lose it if something happens.

While waiting for the model to finish talking, I can prepare my next question inside the input box, using it as a draft that is ready to be sent next when the streamed text will become white.

If I would save the state – either to browser slot or download as a JSON saved story – it won't contain the current streamed yellow text, and also won't contain my current draft inside the input box.

This will be more important for slow systems and large models, since almost all of person's time is spent waiting the end of turn! So no matter when the user saves – he would either have an ongoing streaming, or his next prepared text in the prompt field.

Technically you can cut the prompt and paste it anywhere inside the Memory popup – and it will get saved now. Just don't forget to restore it again, and be double-sure when loading such JSON history since you may not notice that your memory or author's note are not empty / correct.

The preservation of the yellow text is even more challenging, since it cancels the selection at each streaming update, leaving only Ctrl+A and Ctrl+C feasible for grabbing the content!

(In JSON, the yellow text can be concatenated as-is, while the input prompt should have its own key to be correctly restored when loading back)

**Comment by aleksusklim** [comment]
By the way, can you also include the name of the current model (when it is known; you are already displaying it in green) to JSON saves?

Because the sampler settings are often depend on the model, and if I load one of many old stories (personally I have several hundreds already) – I cannot remember which model I have used for that particular story!
For example, to quickly recall what settings were needed for a particular model – I can naturally check my stories saved from it if there would be a way. (Even a simple text search thought files would be enough for this, as long as the model is mentioned anywhere)

As for displaying, you can replace/append the green text with loaded model info right after reading the story from JSON, up till the next request would be sent (replacing the green line back to the current served model).

**Comment by LostRuins** [comment]
Why not just add it to the json filename? The name is persisted through multiple saves. 

I generally try to avoid storing temporary state information within the JSON files. It's intended for settings and the story only. I personally think it would just add clutter if i store such temporary info - next time people might as for generation speed and timings too. 

Quick poll: would other people really want to see the last used model name in a save file? Please add your thoughts. It's not hard to add, but it feels unnecessary and mostly pointless.

**Comment by aleksusklim** [comment]
I can propose a more general solution!

Add just one free multiline input field, let's say in `Save / Load` popup.
It should be titled (or have hint placeholder) like `Notes for your current story (saved to JSON, have no effect on generation)`

This way the user could put there whatever he wants, for example:
- The model name, copypasted (instead of putting in to the name of saved file)
- Draft text from the input during a generation (that I wanted to be saved automatically)
- A bunch of system prompts to be used as templates on demand (transferable between autosaved stories)
- Interesting results of otherwise retried generations (I often had to save an extra story each time I see something outstanding but don't want to keep it in the history)
- Proper names of characters or places to use as a quick reference (instead of searching for them in past actions)
- Sampler parameters that work good together (and they will be always at hand)

This field should be saved and loaded to JSON, but it should *not* be cleared when starting a new scenario!
So that the contents would be "global", transferable between new stories.

You can even make it like this: whenever your code needs to replace the content of this field – check that `if(new_notes&&new_notes.trim()){` so it would overwrite only with non-empty contents.
This way, opening any old story won't destroy it (good for keeping global stuff there).

Don't worry, the user will not be confused because this field is visible in front of your eyes just as you click on `Save / Load`, and if you don't want it to be kept – then just Ctrl+A and Delete the text.

I can imagine how my recently played story will contain everything I need to start any other mode I might want (system prompt, sampler settings template, start/end sequences, stop words) – and I would just copypaste it to correct boxes! Instead of searching among my JSONs in attempt to find one with similar story mode that I want to mimic…

**Comment by LostRuins** [comment]
Not a bad idea. now i just need to find a clean place to put it in the ui....

**Comment by LostRuins** [comment]
Okay, this is now added. Check it out at https://lite.koboldai.net 

You can access your "Personal Notes" from the memory panel. Feel free to store anything you need into it.

**Comment by aleksusklim** [comment]
Umm… I don't like it.

Two clicks are too much for using this regularly!
Also it is too close to `AutoGenerate Memory` action; more natural could be beside `Logit Biases` instead.

You are also not preserving this field when starting a new game EVEN if `Keep Memory and World Info?` is checked when clicking on `New Session`!

I was hoping you would add this field to just `Save File / Load File / Export File` popup (right when clicking `Save / Load`), at the bottom – so it would be visible before saving the story…

Hmm, maybe a third tab in Settings might do the work, because the `Settings` popup remembers the last used tab, which would allow to open Notes with one click.

Anyway, I see many reasons why I would want to change something in Notes right before saving, and if it will be in Settings – I think this would be still inconvenient.

If you don't want to make a separate field (relying this on textarea popup), then just move the button to `Save / Load` popup. But where… You don't want it to have a custom icon and to be located to the right of `Share`, do you?
Maybe to the right of `Temporary Browser Storage`, there seems to be unused column space. But it will look awkward unless you'd add proper margins to it.

Also, I noticed you have `Show Advanced Load` checkbox? It shows 6 categories of what can be loaded – and Notes logically should go to one of those, right? Or maybe have a dedicated one for itself.

P.S.
When `inputBox()` is called, can you give the keyboard focus to `inputboxcontainerinputarea` to spare another extra click?

**Comment by LostRuins** [comment]
> Also it is too close to AutoGenerate Memory action; more natural could be beside Logit Biases instead.

There's not enough empty space next to the logit bias button. It's already quite cramped. In any case this field shouldn't really be used too often - after all the original request was just to note down the model names.

![image](https://github.com/LostRuins/lite.koboldai.net/assets/39025047/d2d990b2-dfa4-4a08-b184-7c26df9fe44e)

> You are also not preserving this field when starting a new game EVEN if Keep Memory and World Info? is checked when clicking on New Session!

Will fix.

> Also, I noticed you have Show Advanced Load checkbox? It shows 6 categories of what can be loaded – and Notes logically should go to one of those, right? Or maybe have a dedicated one for itself.

I will tie it to the memory toggle.

> When inputBox() is called, can you give the keyboard focus to inputboxcontainerinputarea to spare another extra click?

Hmm I dunno. This behavior will be a bit annoying on mobile since it will cause the virtual keyboard to pop out and resize the viewport. For example, maybe you just wanna check your old notes, suddenly, the screen gets resized.

**Comment by aleksusklim** [comment]
Okay, I didn't think about mobile layout.

I was about suggesting at least make the button larger (naming it "Personal Notes") or add margins between "AutoGenerate Memory"; but looking at your provided screenshot clarifies that actually everything is positioned quite nicely!

> this field shouldn't really be used too often

Oh, I got it. I can copypaste from it to Notepad after loading a previous story, then use Notepad in another window to keep my notes, and then just copypaste back once I decide to save the story.
It won't hate the autosave ability, but that can be tolerated.

Looks like this can be called solved and thus closed. Thanks!
