### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by scavru** [LostRuins/lite.koboldai.net#65]
ability to run scenarios from local cards, yes, I can load a character card, but I'd like a scenario, because V2 cards support it.
When I open the character card I can't see the scenario, I have to go into memory and look there.

**Comment by LostRuins** [comment]
What does the scenario contain?

**Comment by scavru** [comment]
I may have misunderstood, as soon as I find the card I saw it on I'll reopen it, sorry for the inconvenience.

**Comment by henk717** [comment]
For us that is World Info

**Comment by scavru** [comment]
I just saw on some scenarios with chub.ai was the first message from Bot with a description of the scenario, and when loading from the card the beginning was with "first message". And may be you can add a setting that would be the first to output the scenario, because there are a lot of cards and for the scenario have to climb into memory.  it would just be really convenient. For example load card:
Scenario Bot message: {{user}}, a Saiyan from Universe 6 is camping in a field on Planet Sadala without imagining that would run into {{char}}, who was training nearby. Everything is set in the Dragon Ball universe.
First message:.....
