### ISSUE TITLE
Probability of Triggering World Info Entries is Inverted

### ISSUE THREAD

**Issue by Reithan** [LostRuins/lite.koboldai.net#74]
https://github.com/LostRuins/lite.koboldai.net/blob/cf69c2b31031d8ff8b47abda8354d0ebed8527bc/index.html#L10530

The code rolls a 1-100 value from `Math.random()` then compares it to the probability and triggers the entry if the roll is >= the probability, meaning the probability is actually the probability it WON'T be triggered, right now.

Example:
If probability for a key is 10%, rolls 1-9 won't trigger it, while rolls 10-100 will, giving it a 90% chance to trigger, rather than 10%.

**Comment by LostRuins** [comment]
Good catch, thanks. I'll fix it.

**Comment by Reithan** [comment]
Tested again on last night's release and it looks good. :D

**Comment by LostRuins** [comment]
Yeap, fix is live. Thanks for helping to spot it
