### ISSUE TITLE
The ETA for the next generated message has become incredibly inaccurate

### ISSUE THREAD

**Issue by NintendoManiac64** [LostRuins/lite.koboldai.net#8]
As of maybe a week ago, I've noticed that the ETA for the next upcoming generated message seems to have become more and more inaccurate, and it may also be more inaccurate the shorter the actual generated message time is.

In particular, sub 20-second generations are now displaying ETAs greater than 150 which is just incredibly inaccurate as shown in the following video that I recorded using the Linux Mint Xfce 21.1 live ISO (which by its nature is an extremely reproducible environment):

[video.webm](https://user-images.githubusercontent.com/11896003/230543200-b3dde0d9-ab6a-4dfd-9513-3b7e41f04831.webm)

**Comment by LostRuins** [comment]
Ah okay there's a bit of a misconception here. The number you see is not an ETA in seconds, it is your **queue position**. What this means is there are actually 180 requests ahead of you in the queue. However, not all the requests may be fulfillable by the worker, so those can get skipped, and also you get to "jump queue" based on the amount of kudos you have giving you extra priority.

This issue cannot be fixed on the client side, but will require some enhancements on the AI Horde. If enhancement https://github.com/db0/AI-Horde/issues/204 gets implemented the queue and queue position counter should become more accurate as unfulfillable requests are excluded.

**Comment by LostRuins** [comment]
Closing as can't fix, please follow up on Horde repo to pursue this further.
