### ISSUE TITLE
Feature Request: Add a Speech Rate slider to TTS Settings if it doesn't already exist. If it does already exist, expose it to a11y.

### ISSUE THREAD

**Issue by jeffkelly2020** [LostRuins/lite.koboldai.net#80]
Hi,

First of all, I am a screen reader user, and the UI for Kobold lite provides an excellent user experience in my situation. Many thanks for the excellent work!
That said, one feature I'm not finding is a speech rate slider in TTS settings.  In light of the good accessibility throughout the rest of the UI, I'm guessing that this control just doesn't exist yet, and this isn't a matter of the control not being exposed to the screen reader. Either way though, a speech rate slider would be a great feature add if possible.
Thanks,

**Comment by LostRuins** [comment]
Added a simple selector for narrator speed, please give it a try. 

Note that it only affects browser based TTS - external TTS API servers like XTTS or AllTalk will not be able to change speed yet.

**Comment by jeffkelly2020** [comment]
Perfect. This works great. Many thanks!!!
