### ISSUE TITLE
Custom image model name with OpenAI API

### ISSUE THREAD

**Issue by IS2511** [LostRuins/lite.koboldai.net#88]
I would very much appreciate it if the image generation settings supported a custom model name when using the OpenAI API format (currently the "OpenAI DALL-E" option), similar to how text model settings support a custom model name.

Some 3rd-party APIs use the OpenAI format but support more than just OpenAI models, including image to text models. This is my main use case. Seems like a reasonable option to have.

Suggested issue tags: enhancement

**Comment by LostRuins** [comment]
Added, please try it

**Comment by IS2511** [comment]
It works. Thank you!
