### ISSUE TITLE
In 'edit' mode, clicking in message conversation history but not actually making edits clears "redo"

### ISSUE THREAD

**Issue by NintendoManiac64** [LostRuins/lite.koboldai.net#9]
Simply put, in 'edit' mode, if you click in the message conversation history box but then don't actually make any edits (e.g. you delete nothing and you type nothing, not even a space or delete line-breaks), it'll cause any "redo" history to be cleared.

**Comment by LostRuins** [comment]
does not seem to be present any longer. Please reopen a new issue if this is still a problem.
