### ISSUE TITLE
Chat Completions UI for Anthropic API (like OpenAI API)

### ISSUE THREAD

**Issue by IS2511** [LostRuins/lite.koboldai.net#95]
The API endpoints for OpenAI Chat Completions and Anthropic Messages are pretty similar iirc. Can you please add a similar interface to the Anthropic API menu as in the OpenAI API menu? Thanks!

I was previously using a service that offers all models in the OpenAI API format, but now want to switch to a different one that offers APIs in the original format. This breaks my current flow because I frequently used Anthropic models via the same OpenAI API format. Now that I am forced to use the Anthropic API format, I can no longer specify Chat Completions, which should be possible with Anthropic too (even if under a different name).

Suggested issue tags: enhancement

**Comment by LostRuins** [comment]
What do you mean by "can no longer specify Chat Completions"? Anthropic models require the use of their API and has a fixed format for each model. Can you elaborate more on how it breaks your current flow?

**Comment by IS2511** [comment]
I'm so dumb. I didn't see the "System Prompt" and "Assistant Postfix" inputs in the Anthropic API menu because they were hidden for `claude-2` (selected by default). I just had to switch the model first.

My only suggestion is to maybe change the default model for Anthropic to one of the recent ones?

Sorry for wasting time. Closing this as invalid.
